name: CI

on:
  push:
    branches: [ main, codegen-bot/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

  build-swift:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build Swift CLI
      run: |
        cd peekaboo-cli
        swift build -c release
    
    - name: Test Swift CLI
      run: |
        cd peekaboo-cli
        swift run peekaboo --help
